### ISSUE TITLE
High Sierra

### ISSUE THREAD

**Issue by chrisbroski** [ysalathe/GenericUSBMIDI#9]
I tried to build on 10.13.1 but I am getting semantic issue errors `Use of undeclared identifier 'errexit'`

**Comment by elliottjohnson** [comment]
Not sure if you are interested, but I have an open pull request that addresses this for xcode 9.2 on osx 10.13.4

**Comment by setton1** [comment]
Hey Elliott - how far did you get with this in the end? trying to resurrect the PC-300 hardware on mac 10.14.3 Mojave. Followed your changes in the pull request so i am now able to compile as i had the same errors shown here (thank you!), but mac not detecting the hardware / driver and dont know how to debug!

**Comment by elliottjohnson** [comment]
Setton1, I've not looked at it in a while.  I no longer have a PC300 (someone actually stole it, can't believe it was worth stealing) and I've yet to upgrade to Mojave on my mac, so sorry I can't be of much help.

**Comment by ysalathe** [comment]
Unfortunately, I also do no longer own a PC300 anymore. I sold it, to get some space in our flat. Is somebody interested in taking over this project?

**Comment by setton1** [comment]
@elliottjohnson i worked out how to compile and it works on Mojave! thank you very much for this. it is wonderful to see new life in old hardware. Sorry yours got stolen...the irony is that they are now able to use it thanks to you!

**Comment by dimitre** [comment]
@setton1 how did you do? thank you

**Comment by setton1** [comment]
worked perfectly. i downloaded and compiled in XCode per instructions and worked great!

**Comment by nunoflores** [comment]
Just build for Mojave, and worked fine (using a PC-300)! Thanks a lot!
